export const FETCH_GRID_DATA_REQUEST = "FETCH_GRID_DATA_REQUEST";
export const FETCH_GRID_DATA_SUCCESS = "FETCH_GRID_DATA_SUCCESS";
export const FETCH_GRID_DATA_FAILURE = "FETCH_GRID_DATA_FAILURE";

export const ADD_SECTION_REQUEST = "ADD_SECTION_REQUEST";
export const ADD_SECTION_SUCCESS = "ADD_SECTION_SUCCESS";

export const UPDATE_SECTION_REQUEST = "UPDATE_SECTION_REQUEST";
export const UPDATE_SECTION_SUCCESS = "UPDATE_SECTION_SUCCESS";

export const DELETE_SECTION_REQUEST = "DELETE_SECTION_REQUEST";
export const DELETE_SECTION_SUCCESS = "DELETE_SECTION_SUCCESS";

export const COPY_SECTION_REQUEST = "COPY_SECTION_REQUEST";
export const COPY_SECTION_SUCCESS = "COPY_SECTION_SUCCESS";

export const ADD_ITEM_REQUEST = "ADD_ITEM_REQUEST";
export const ADD_ITEM_SUCCESS = "ADD_ITEM_SUCCESS";

export const DELETE_ITEM_REQUEST = "DELETE_ITEM_REQUEST";
export const DELETE_ITEM_SUCCESS = "DELETE_ITEM_SUCCESS";

export const MOVE_SECTION_REQUEST = "MOVE_SECTION_REQUEST";
export const MOVE_SECTION_SUCCESS = "MOVE_SECTION_SUCCESS";

export const MOVE_ROW_BETWEEN_SECTIONS = "MOVE_ROW_BETWEEN_SECTIONS";
export const UPDATE_SECTION_ROWS_SUCCESS = "UPDATE_SECTION_ROWS_SUCCESS";
export const UPDATE_GROUPED_ITEMS_DND = "UPDATE_GROUPED_ITEMS_DND";

export const UPDATE_ITEM_IN_SECTION = "UPDATE_ITEM_IN_SECTION";
export const UPDATE_ITEM_IN_SECTION_SUCCESS = "UPDATE_ITEM_IN_SECTION_SUCCESS";
export const UPDATE_ITEM_IN_SECTION_FAILURE = "UPDATE_ITEM_IN_SECTION_FAILURE";
